server {
    listen 80 default_server;
    listen [::]:80 default_server;
    
    root /var/lib/nginx/html;
    index index.html;
    
    location / {
        return 200 'Hello from nginx';
    }
}
